const SUCCESS = 200;
const INTERNAL_SERVER = 500;
const CONFLICT_ERROR = 409;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const NO_ROUTE_ERROR = 404;
const NOT_ACCEPTABLE = 406;
const BAD_REQUEST = 400;

export {
   SUCCESS, INTERNAL_SERVER, CONFLICT_ERROR, UNAUTHORIZED, FORBIDDEN, NO_ROUTE_ERROR, NOT_ACCEPTABLE, BAD_REQUEST
}